# Generated by Django 5.1.3 on 2024-11-24 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                ("content", models.CharField(max_length=2000)),
                ("hit", models.IntegerField(default=0)),
                ("group", models.IntegerField(default=0)),
                ("step", models.IntegerField(default=0)),
                ("indent", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
