# Generated by Django 5.1.2 on 2024-11-25 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0002_board_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="board",
            old_name="author",
            new_name="user",
        ),
    ]
